"""Изменил схему и модель deployment

Revision ID: fb51e4df9832
Revises: fa2b4e6a94b0
Create Date: 2025-07-25 03:42:52.751408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb51e4df9832'
down_revision: Union[str, None] = 'fa2b4e6a94b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deployments', 'provider',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('VERCEL', 'NETLIFY', 'GITHUB_PAGES', name='providertype'),
               existing_nullable=False)
    op.alter_column('deployments', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'ACTIVE', 'FAILED', name='deploymentstatus'),
               existing_nullable=False)
    op.alter_column('projects', 'template_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'template_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('deployments', 'status',
               existing_type=sa.Enum('PENDING', 'ACTIVE', 'FAILED', name='deploymentstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('deployments', 'provider',
               existing_type=sa.Enum('VERCEL', 'NETLIFY', 'GITHUB_PAGES', name='providertype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
